/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.solosis;

/**
 *
 * @author Heber
 */
public class VentanaTokens extends javax.swing.JDialog {
 
    public VentanaTokens(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Análisis Léxico – Tokens Solosis");
    }
 
    /** Convierte el nombre interno del patrón al patrón regex legible. */
    private static String resolverPatronLegible(String nombrePatron) {
        switch (nombrePatron) {
            case "PALABRA_RESERVADA_GABITE": return "gabite";
            case "PALABRA_RESERVADA_ESPEON": return "espeon";
            case "PALABRA_RESERVADA_FALINK": return "falink";
            case "PALABRA_RESERVADA_MEOWL":  return "meowl";
            case "LITERAL_ENTERO":           return "[0-9]+";
            case "LITERAL_DECIMAL":          return "[0-9]+\\.[0-9]+";
            case "LITERAL_STRING":           return "\"[^\"]*\"";
            case "IDENTIFICADOR":            return "[a-zA-Z_][a-zA-Z0-9_]*";
            case "ASIGNACION":               return "\\?";
            case "OPERADOR_SUMA":            return "\\+";
            case "OPERADOR_RESTA":           return "-";
            case "OPERADOR_MULT":            return "\\*";
            case "OPERADOR_DIV":             return "/";
            case "PUNTO_COMA":               return ";";
            case "COMENTARIO":               return "#.*";
            default:                          return nombrePatron;
        }
    }
 
    /** Llena la tabla con los datos de los tokens incluyendo lexema y patrón. */
    public void llenarTabla(java.util.List<Object[]> datos) {
        javax.swing.table.DefaultTableModel modelo =
                (javax.swing.table.DefaultTableModel) tblTokens.getModel();
        modelo.setRowCount(0);
 
        // ← SE AGREGÓ "?" Y "meowl" COMO PALABRAS RESERVADAS
        java.util.Set<String> reservadas = new java.util.HashSet<>(java.util.Arrays.asList(
            "gabite", "espeon", "falink", "meowl", "?"
        ));
 
        int contador = 1;  // Bug 1 fix: contador incremental para No. Lista
 
        for (Object[] fila : datos) {
            String tipo    = fila[0] != null ? fila[0].toString() : "";
            String lexema  = fila[1] != null ? fila[1].toString() : "";
            String patron  = fila[2] != null ? fila[2].toString() : "";
            Object linea   = fila[3];
            Object columna = fila[4];
 
            String esReservada = reservadas.contains(lexema.toLowerCase()) ? "Sí" : "No";
            String patronLegible = resolverPatronLegible(patron);  // Bug 2 fix: patrón legible
 
            modelo.addRow(new Object[]{ contador, tipo, lexema, patronLegible, linea, columna, esReservada });
            contador++;  // Bug 1 fix: incrementar después de cada fila
        }
    }

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane = new javax.swing.JScrollPane();
        tblTokens = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No. Lista", "Tipo", "Valor", "Linea", "Colunma", "Palabra reservada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPane.setViewportView(tblTokens);
        if (tblTokens.getColumnModel().getColumnCount() > 0) {
            tblTokens.getColumnModel().getColumn(0).setResizable(false);
            tblTokens.getColumnModel().getColumn(1).setResizable(false);
            tblTokens.getColumnModel().getColumn(2).setResizable(false);
            tblTokens.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaTokens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaTokens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaTokens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaTokens.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaTokens dialog = new VentanaTokens(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JButton jButton1;
    private javax.swing.JTable tblTokens;
    // End of variables declaration//GEN-END:variables
}
