/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.solosis;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author Heber
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        this.setLocationRelativeTo(null);
        // Colores tipo VS Code para el editor
        txtEntrada.setBackground(new Color(30, 30, 30));
        txtEntrada.setForeground(Color.WHITE);
        txtEntrada.setCaretColor(Color.WHITE); // El cursor que parpadea
        txtEntrada.setFont(new Font("Consolas", Font.PLAIN, 14));
 
        // Colores para la consola de salida
        txtSalida.setBackground(new Color(20, 20, 20));
        txtSalida.setForeground(Color.CYAN);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEntrada = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSalida = new javax.swing.JTextArea();
        panelBotones = new javax.swing.JPanel();
        btnAnalizar = new javax.swing.JButton();
        btnTokens = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtEntrada.setColumns(20);
        txtEntrada.setRows(5);
        jScrollPane2.setViewportView(txtEntrada);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txtSalida.setColumns(20);
        txtSalida.setRows(5);
        jScrollPane3.setViewportView(txtSalida);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
        );

        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });
        panelBotones.add(btnAnalizar);

        btnTokens.setText("Ver Tokens");
        btnTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTokensActionPerformed(evt);
            }
        });
        panelBotones.add(btnTokens);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTokensActionPerformed
        java.util.ArrayList<Object[]> listaTokens = new java.util.ArrayList<>();
        String codigo = txtEntrada.getText();
 
        try {
            // Usar el AnalizadorManual para obtener lexemas y patrones
            AnalizadorManual analizador = new AnalizadorManual();
            java.util.List<AnalizadorManual.Token> tokens = analizador.escanear(codigo);
 
            for (AnalizadorManual.Token tok : tokens) {
                String tipo    = tok.tipo.toString();
                String lexema  = tok.lexema;
                String patron  = tok.patron;
                int    linea   = tok.linea;
                int    columna = tok.columna;
                // fila: [tipo, lexema, patron, linea, columna]
                listaTokens.add(new Object[]{ tipo, lexema, patron, linea, columna });
            }
 
            VentanaTokens vt = new VentanaTokens(this, true);
            vt.llenarTabla(listaTokens);
            vt.setLocationRelativeTo(null);
            vt.setVisible(true);
 
        } catch (ExcepcionLexica e) {
            txtSalida.setForeground(java.awt.Color.RED);
            txtSalida.setText(e.getMessage());
        } catch (ExcepcionLimite e) {
            txtSalida.setForeground(java.awt.Color.RED);
            txtSalida.setText(e.getMessage());
        } catch (Exception e) {
            txtSalida.setForeground(java.awt.Color.RED);
            txtSalida.setText("Error en el análisis léxico: " + e.getMessage());
        }

    }//GEN-LAST:event_btnTokensActionPerformed

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        String codigo = txtEntrada.getText();
        txtSalida.setText("");
        
        List<String> erroresSintacticos = new ArrayList<>();
        String[] lineas = codigo.split("\n");
        Steelix validador = new Steelix();
 
        // Fase 1: Validación Estructural (Sintáctica) sin detener el bucle
        for (int i = 0; i < lineas.length; i++) {
            String lineaTexto = lineas[i].trim();
            if (lineaTexto.isEmpty() || lineaTexto.startsWith("#")) {
                continue; // Ignorar líneas vacías o comentarios puros
            }
            try {
                validador.validarLinea(lineas[i], i + 1);
            } catch (ExcepcionSintactica | ExcepcionSemantica e) {
                erroresSintacticos.add("Línea " + (i + 1) + ": " + e.getMessage());
            } catch (Exception e) {
                erroresSintacticos.add("Error crítico línea " + (i + 1) + ": " + e.getMessage());
            }
        }
 
        // Si hay errores de estructura graves (ej: falta un ';'), los mostramos en ROJO de golpe
        if (!erroresSintacticos.isEmpty()) {
            txtSalida.setForeground(Color.RED);
            txtSalida.append("❌ SE ENCONTRARON ERRORES SINTÁCTICOS EN EL PROGRAMA:\n");
            txtSalida.append("───────────────────────────────────────────────────\n");
            for (String err : erroresSintacticos) {
                txtSalida.append(err + "\n");
            }
            txtSalida.append("───────────────────────────────────────────────────\n");
            txtSalida.append("\n>>> ANÁLISIS SINTÁCTICO ABORTADO <<<");
            return;
        }
 
        // Fase 2: Análisis Léxico y Ejecución Dinámica con acumulación de errores de tipo
        try {
            AnalizadorManual lexer = new AnalizadorManual();
            List<AnalizadorManual.Token> tokens = lexer.escanear(codigo);
 
            Interprete ejecutor = new Interprete();
            ejecutor.ejecutar(tokens);
 
            String resultadoLog = ejecutor.obtenerLogEjecucion();
            
            // Condición infalible: si el log contiene la cruz o la palabra reservada de fallo
            if (resultadoLog.contains("ERRor") || resultadoLog.contains("ABORTADA")) {
                txtSalida.setForeground(Color.RED); // ¡Pintar en ROJO pasional si falló algo semántico!
            } else {
                txtSalida.setForeground(new Color(0, 150, 0)); // VERDE éxito si corrió limpio
            }
            
            txtSalida.setText(resultadoLog);
 
        } catch (ExcepcionLexica e) {
            txtSalida.setForeground(Color.RED);
            txtSalida.setText("Error Léxico: " + e.getMessage());
        } catch (ExcepcionLimite e) {
            txtSalida.setForeground(Color.RED);
            txtSalida.setText("Error de Límites: " + e.getMessage());
        } catch (Exception e) {
            txtSalida.setForeground(Color.RED);
            txtSalida.setText("ERROR CRÍTICO DE SISTEMA: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAnalizarActionPerformed
    
    private String obtenerNombreToken(int id) {
        switch (id) {
            case sym.GABITE: return "TIPO_INT (GABITE)";
            case sym.ESPEON: return "TIPO_DECIMAL (ESPEON)";
            case sym.FALINK: return "TIPO_STRING (FALINK)";
            case sym.ENTERO: return "VALOR_ENTERO (GABITE)";
            case sym.STRING: return "VALOR_CADENA (FALINK)";
            case sym.ASIGNACION: return "ASIGNACION (=)";
            case sym.SUMA: return "OPERADOR_SUMA (+)";
            case sym.RESTA: return "OPERADOR_RESTA (-)";
            case sym.MULT: return "OPERADOR_MULT (*)";
            case sym.DIV: return "OPERADOR_DIV (/)";
            case sym.ID: return "IDENTIFICADOR (NOMBRE)";
            case sym.EOF: return "FIN_DE_ARCHIVO";
            
            case sym.LIZARD: return "CICLO_DO (LIZARD)";
            case sym.PURPLE_LIZARD: return "CONDICION_WHILE (purple_lizard)";
            case sym.PARENTESIS_A: return "PARENTESIS_APERTURA";
            case sym.PARENTESIS_C: return "PARENTESIS_CIERRE";
            case sym.LLAVE_A: return "LLAVE_APERTURA";
            case sym.LLAVE_C: return "LLAVE_CIERRE";
            
           
            default: return "TOKEN_OTRO (" + id + ")";
            
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnTokens;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JTextArea txtEntrada;
    private javax.swing.JTextArea txtSalida;
    // End of variables declaration//GEN-END:variables
}
